language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
    global:
        - SYMFONY_ENV=test

matrix:
    fast_finish: true
    allow_failures:
        - php: 7.0
    include:
        - php: 5.5
          env: COVERAGE=true

install:
    - make COMPOSEROPTS="--prefer-dist --no-interaction" deps

before_script:
#    - php bin/console doctrine:schema:update --force

script:
    - make test
