language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 7.0
    - 7.1

env:
    global:
        - SYMFONY_ENV=test

branches:
    except:
        - /^analysis-.*$/

matrix:
    fast_finish: true
    allow_failures:
        - php: 7.1
    include:
        - php: 7.0
          env: COVERAGE=true

before_install:
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi

install:
    - make COMPOSEROPTS="--prefer-dist --no-interaction" deps

before_script:
    - bin/console doctrine:database:create --if-not-exists
    - make setup

script:
    - make test
