language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 7.0
    - 7.1

env:
    global:
        - SYMFONY_ENV=test

matrix:
    fast_finish: true
    include:
        - php: 7.0
          env: COVERAGE=true

install:
    - make COMPOSEROPTS="--prefer-dist --no-interaction" deps

before_script:
    - make TEST=true setup

script:
    - make test
