version: '2'

services:
    data:
        image: debian:jessie
        volumes:
            - .:/app
        tty: true

    db:
        extends:
            file: etc/docker/common/db/docker-compose.yml
            service: db
        volumes:
            - ./var/docker/dev/mysql:/var/lib/mysql

    app:
        build: etc/docker/dev/app
        volumes_from:
            - data
        links:
            - db
            - blackfire
        environment:
            HISTFILE: /app/var/docker/dev/.bash_history
            XDG_CONFIG_HOME: /app/var/docker/dev/.config # Required for PsySH
            COMPOSER_HOME: /app/var/docker/dev/composer
        mem_limit: 2000000000

    web:
        build: etc/docker/dev/web
        ports:
            - 80
        links:
            - app
        volumes_from:
            - data

    app_debug:
        build:
            context: etc/docker/dev/app
            args:
               USE_XDEBUG: "yes"
        volumes_from:
            - data
        links:
            - db
            - blackfire
        environment:
            HISTFILE: /app/var/docker/dev/.bash_history
            XDG_CONFIG_HOME: /app/var/docker/dev/.config # Required for PsySH
            COMPOSER_HOME: /app/var/docker/dev/composer
        mem_limit: 2000000000

    web_debug:
        build: etc/docker/dev/web
        ports:
            - 80
        links:
            - app_debug:app
        volumes_from:
            - data

    # Set your blackfire IDs and tokens as environment variables
    # in docker-compose.override.yml before building the containers.
    # You can find your IDs and tokens in your account profile
    # https://blackfire.io/account or on the blackfire docker
    # integration page: https://blackfire.io/docs/integrations/docker
    blackfire:
        image: blackfire/blackfire
