imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: extras.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig', 'php'] # PHP engine required by Oro
        assets_version: %assets_version%
        assets_version_format: %%s?version=%%s
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.storage_dir%/var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    exception_controller: "FOS\RestBundle\Controller\ExceptionController::showAction"
    globals:
        bap:
            layout: ::base.html.twig  # default layout across all Oro bundles

# Assetic Configuration (used by Oro)
assetic:
    debug:                    false
    use_controller:           false
    filters:
        cssrewrite: ~
        lessphp:
            file: %kernel.storage_dir%/vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"
            paths: ["%kernel.root_dir%/../web/bundles"]
        cssmin: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#
# Oro configuration requirements
#
fos_rest:
    body_listener:
        decoders:
            json: fos_rest.decoder.json
    view:
        failed_validation:    HTTP_BAD_REQUEST
        default_engine:       php
        formats:
            json:             true
            xml:              false
    format_listener:
        rules:
            - { path: '^/api/rest', priorities: [ json ], fallback_format: json, prefer_extension: false }
            - { path: '^/api/soap', stop: true }
            - { path: '^/', stop: true }
    routing_loader:
        default_format:       json

fos_js_routing:
    routes_to_expose:         [oro_*]

be_simple_soap:
    cache:
        type:                 disk
        lifetime:             86400
        limit:                5
    services:
        soap:
            namespace:        urn:OroPlatform
            binding:          rpc-literal
            resource:         .
            resource_type:    oro_soap

stof_doctrine_extensions:
    default_locale: en
    translation_fallback: true
    orm:
        default:
            translatable:     true
            tree:             true

escape_wsse_authentication:
    authentication_provider_class: Oro\Bundle\UserBundle\Security\WsseAuthProvider
    authentication_listener_class: Oro\Bundle\UserBundle\Security\WsseAuthListener

genemu_form:
    select2: ~
    autocomplete: ~

a2lix_translation_form:
    locales: [en]
    templating: "OroUIBundle:Form:translatable.html.twig"


# Overriden Oro default
knp_gaufrette:
    adapters:
        attachments:
            local:
                directory: %kernel.storage_dir%/var/attachments

#
# ORO Bundles config
#
oro_distribution:
    entry_point: ~

oro_require_js:
    build_path:               "js/oro.min.js"
    building_timeout:         3600
    build:
        preserveLicenseComments: true

oro_help:
    defaults:
        server: http://help.orocrm.com/
        prefix: Third_Party
    vendors:
        Oro:
            prefix: ~
            alias: Platform
    routes:
        oro_default:
            uri: Platform/OroDashboardBundle

oro_theme:
    active_theme: oro
