---
- hosts: all
  become: true
  vars_files:
    - vars/all.yml
    - vars/config.yml
  roles:
    - server
    - nginx
    - mariadb
    - php
    - blackfire
    - xdebug
    - composer
    - nodejs
    - app
